# Codecov configuration
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true
